version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: training-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: training_db
      MYSQL_USER: nodeuser
      MYSQL_PASSWORD: nodepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
